/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import com.microsoft.sqlserver.jdbc.StringUtils;
import controller.AdminController;
import controller.SinhvienController;
import entity.AccountEntity;
import entity.HocPhanEntity;
import entity.SinhVienEntity;
import java.awt.CardLayout;
import java.awt.Color;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import util.HibernateUtil;
import view.LoginForm;
import static view.LoginForm.getHash;
import org.apache.commons.lang3.math.NumberUtils;

/**
 *
 * @author Dell
 */
public class AdminMenu extends javax.swing.JFrame {
    private String userName;
    private AdminController admincontroller;
    private SinhvienController sinhviencontroller;
    /**
     * Creates new form MainMenu
     */   
    CardLayout cardLayout;    
    public AdminMenu(String userName){
        this.userName = userName;
        initComponents();
        setResizable(true);
        helloLabel.setText("<html>Xin chào bạn <b>" + userName + "</b></html>");
        cardLayout = (CardLayout)(cardlayouttab.getLayout());
        cardlayouttab.removeAll();
        cardlayouttab.add(card1);
        cardlayouttab.repaint();
        cardlayouttab.revalidate();
        admincontroller = new AdminController();
        sinhviencontroller = new SinhvienController();
        admincontroller.loadtable(modeltable);
        admincontroller.loadtableUser(tableUser);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        helloLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        sidePanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        accountPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        modulePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        sinhvienpanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cardlayouttab = new javax.swing.JPanel();
        card1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        btnthemtk = new javax.swing.JButton();
        card2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modeltable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        mahocphantxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tenhocphantxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        trongsotxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tinchitxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        vienquanlytxt = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        thoiluongtxt = new javax.swing.JTextField();
        bntxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnluu = new javax.swing.JButton();
        card3 = new javax.swing.JPanel();
        hotenLabel = new javax.swing.JLabel();
        ngaysinhLabel = new javax.swing.JLabel();
        loplabel = new javax.swing.JLabel();
        hehocLabel = new javax.swing.JLabel();
        mssvLabel = new javax.swing.JLabel();
        trangthaiLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        mssvtxt = new javax.swing.JTextField();
        ngaysinhtxt = new javax.swing.JTextField();
        hovatentxt = new javax.swing.JTextField();
        loptxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        hehoctxt = new javax.swing.JTextField();
        btnclose = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        card5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablesinhvien = new javax.swing.JTable();
        btnxoasv = new javax.swing.JButton();
        svtk = new javax.swing.JTextField();
        tk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        titlePanel.setBackground(new java.awt.Color(54, 33, 89));
        titlePanel.setPreferredSize(new java.awt.Dimension(1020, 56));

        helloLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        helloLabel.setForeground(new java.awt.Color(255, 255, 255));
        helloLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Logout");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(titlePanelLayout.createSequentialGroup()
                        .addContainerGap(769, Short.MAX_VALUE)
                        .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 55, 118)));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setLayout(new java.awt.GridLayout(5, 1));

        accountPanel.setBackground(new java.awt.Color(85, 55, 118));
        accountPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accountPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountPanelMousePressed(evt);
            }
        });
        accountPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Quản lý tài khoản");
        accountPanel.add(jLabel3);

        jPanel2.add(accountPanel);

        modulePanel.setBackground(new java.awt.Color(64, 43, 100));
        modulePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modulePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modulePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modulePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modulePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modulePanelMousePressed(evt);
            }
        });
        modulePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Quản lý học phần");
        modulePanel.add(jLabel5);

        jPanel2.add(modulePanel);

        sinhvienpanel.setBackground(new java.awt.Color(64, 43, 100));
        sinhvienpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sinhvienpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinhvienpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sinhvienpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sinhvienpanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sinhvienpanelMousePressed(evt);
            }
        });
        sinhvienpanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Quản lý sinh viên");
        sinhvienpanel.add(jLabel12);

        jPanel2.add(sinhvienpanel);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 105, Short.MAX_VALUE))
        );

        cardlayouttab.setLayout(new java.awt.CardLayout());

        card1.setBackground(new java.awt.Color(255, 255, 255));

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số thứ tự", "Username", "Password", "Loại tài khoản"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableUser);

        btnthemtk.setText("Thêm tài khoản");
        btnthemtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemtkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card1Layout = new javax.swing.GroupLayout(card1);
        card1.setLayout(card1Layout);
        card1Layout.setHorizontalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnthemtk)
                .addContainerGap())
        );
        card1Layout.setVerticalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnthemtk)
                .addGap(18, 18, 18))
        );

        cardlayouttab.add(card1, "card2");

        card2.setBackground(new java.awt.Color(255, 255, 255));

        modeltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã học phần", "Tên học phần", "Số tín chỉ", "Trọng số", "Viện quản lý", "Thời lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(modeltable);

        jLabel1.setText("Mã học phần");

        jLabel2.setText("Tên học phần");

        jLabel4.setText("Trọng số");

        trongsotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trongsotxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Số tín chỉ");

        jLabel7.setText("Viện quản lý");

        btnadd.setText("Thêm");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        jLabel8.setText("Thời lượng");

        bntxoa.setText("Xóa ");
        bntxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntxoaActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnluu.setText("Lưu");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card2Layout = new javax.swing.GroupLayout(card2);
        card2.setLayout(card2Layout);
        card2Layout.setHorizontalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(card2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(25, 25, 25)
                            .addComponent(trongsotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(card2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(22, 22, 22)
                                .addComponent(tinchitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(card2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(tenhocphantxt, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                                .addGroup(card2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(mahocphantxt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(card2Layout.createSequentialGroup()
                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thoiluongtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vienquanlytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntxoa)
                    .addComponent(btnadd)
                    .addComponent(btnsua)
                    .addComponent(btnluu))
                .addGap(657, 657, 657))
            .addGroup(card2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE)
                .addContainerGap())
        );
        card2Layout.setVerticalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mahocphantxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tenhocphantxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntxoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tinchitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(trongsotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnluu))
                .addGap(18, 18, 18)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(vienquanlytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(thoiluongtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardlayouttab.add(card2, "card3");

        hotenLabel.setText("Họ và tên:");

        ngaysinhLabel.setText("Ngày sinh:");

        loplabel.setText("Lớp:");

        hehocLabel.setText("Hệ học:");

        mssvLabel.setText("Mã sinh viên:");

        trangthaiLabel.setText("Trạng thái:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Thông tin sinh viên");

        emailLabel.setText("Email");

        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        btnupdate.setText("Tạo");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Đăng kí tài khoản sinh viên với tk = mssv, mk = mssv");

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang học", "Bảo lưu" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card3Layout = new javax.swing.GroupLayout(card3);
        card3.setLayout(card3Layout);
        card3Layout.setHorizontalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card3Layout.createSequentialGroup()
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card3Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(card3Layout.createSequentialGroup()
                                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(trangthaiLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hehocLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loplabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ngaysinhLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hehoctxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(loptxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ngaysinhtxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(card3Layout.createSequentialGroup()
                                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hotenLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mssvLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hovatentxt)
                                    .addComponent(mssvtxt)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addGroup(card3Layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(jLabel9)))))
                    .addGroup(card3Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(btnupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclose)))
                .addContainerGap(454, Short.MAX_VALUE))
        );
        card3Layout.setVerticalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(38, 38, 38)
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mssvtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mssvLabel))
                .addGap(18, 18, 18)
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hovatentxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hotenLabel))
                .addGap(18, 18, 18)
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngaysinhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngaysinhLabel))
                .addGap(15, 15, 15)
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loplabel)
                    .addComponent(loptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hehocLabel)
                    .addComponent(hehoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trangthaiLabel)
                    .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(36, 36, 36)
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate)
                    .addComponent(btnclose)
                    .addComponent(resetbtn))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        cardlayouttab.add(card3, "card4");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Danh sách sinh viên");

        tablesinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Mã số sinh viên", "Họ và tên", "Ngày sinh", "Địa chỉ", "Lớp", "Hệ học", "Trạng thái", "Số điện thoại", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablesinhvien);

        btnxoasv.setText("Xóa");
        btnxoasv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoasvActionPerformed(evt);
            }
        });

        svtk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                svtkMouseEntered(evt);
            }
        });
        svtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svtkActionPerformed(evt);
            }
        });

        tk.setText("Tìm kiếm ");
        tk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card5Layout = new javax.swing.GroupLayout(card5);
        card5.setLayout(card5Layout);
        card5Layout.setHorizontalGroup(
            card5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card5Layout.createSequentialGroup()
                .addContainerGap(478, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(461, 461, 461))
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnxoasv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(svtk, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tk)
                .addGap(27, 27, 27))
        );
        card5Layout.setVerticalGroup(
            card5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card5Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(card5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxoasv)
                    .addComponent(svtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardlayouttab.add(card5, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardlayouttab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(cardlayouttab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void accountPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountPanelMousePressed
   
        
    }//GEN-LAST:event_accountPanelMousePressed

    private void modulePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modulePanelMousePressed

        //((CardLayout)mainPanel.getLayout()).show(mainPanel, "curriculumCard");
        //((CardLayout)moduleManager.getLayout()).show(moduleManager, "menuCurriculumnCard");
    }//GEN-LAST:event_modulePanelMousePressed

    private void accountPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountPanelMouseEntered
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(accountPanel.getBackground().getRGB() != color.getRGB()) {
            accountPanel.setBackground(new java.awt.Color(52,35,82));
        } 
    }//GEN-LAST:event_accountPanelMouseEntered

    private void accountPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountPanelMouseExited
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(accountPanel.getBackground().getRGB() != color.getRGB()) {
            accountPanel.setBackground(new java.awt.Color(64,43,100));
        } 
    }//GEN-LAST:event_accountPanelMouseExited

    private void modulePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modulePanelMouseEntered
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(modulePanel.getBackground().getRGB() != color.getRGB()) {
            modulePanel.setBackground(new java.awt.Color(52,35,82));
        } 
    }//GEN-LAST:event_modulePanelMouseEntered

    private void modulePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modulePanelMouseExited
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(modulePanel.getBackground().getRGB() != color.getRGB()) {
            modulePanel.setBackground(new java.awt.Color(64,43,100));
        } 
    }//GEN-LAST:event_modulePanelMouseExited

    private void goAddAccountTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goAddAccountTabMousePressed

    }//GEN-LAST:event_goAddAccountTabMousePressed

    private void goModifyAccountTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goModifyAccountTabMousePressed
      
    }//GEN-LAST:event_goModifyAccountTabMousePressed

    private void goModuleListTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goModuleListTabMousePressed

        
    }//GEN-LAST:event_goModuleListTabMousePressed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String mahocphan = mahocphantxt.getText();
        String tenhocphan = tenhocphantxt.getText();
        String sotinchistr =tinchitxt.getText();
        String trongsostr = trongsotxt.getText();
        String vienquanly = vienquanlytxt.getText();
        String thoiluong = thoiluongtxt.getText();
        admincontroller.addhp(mahocphan, tenhocphan, sotinchistr, trongsostr, vienquanly, thoiluong,modeltable);
        admincontroller.loadtable(modeltable);
    }//GEN-LAST:event_btnaddActionPerformed

    private void accountPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountPanelMouseClicked
        // TODO add your handling code here:
        cardlayouttab.removeAll();
        cardlayouttab.add(card1);
        cardlayouttab.repaint();
        cardlayouttab.revalidate();
        admincontroller.loadtable(modeltable);
        admincontroller.loadtableUser(tableUser);
    }//GEN-LAST:event_accountPanelMouseClicked

    private void modulePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modulePanelMouseClicked
        // TODO add your handling code here:
                // TODO add your handling code here:
        cardlayouttab.removeAll();
        cardlayouttab.add(card2);
        cardlayouttab.repaint();
        cardlayouttab.revalidate();
        admincontroller.loadtable(modeltable);
    }//GEN-LAST:event_modulePanelMouseClicked

    private void bntxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntxoaActionPerformed
        admincontroller.xoahp(modeltable);
    }//GEN-LAST:event_bntxoaActionPerformed
    private String maHp;

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        int selectedRow = modeltable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để sửa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        maHp = modeltable.getModel().getValueAt(selectedRow, 0).toString();
        try {
            tx = session.beginTransaction();
            Query query = session.createQuery("SELECT hp FROM HocPhanEntity hp WHERE hp.maHp = :maHp");
            query.setParameter("maHp", maHp);
            HocPhanEntity hocphan = (HocPhanEntity) query.uniqueResult();
            if (maHp.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy học phần có mã " + maHp, "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            mahocphantxt.setText(hocphan.getMaHp());
            tenhocphantxt.setText(hocphan.getTenHp());
            thoiluongtxt.setText(hocphan.getThoiLuong());
            tinchitxt.setText(String.valueOf(hocphan.getTinChi()));
            trongsotxt.setText(String.valueOf(hocphan.getTrongSo()));
            vienquanlytxt.setText(hocphan.getTenKhoa());
            tx.commit();
        } catch (HibernateException e) {
            if (tx != null) tx.rollback();
            e.printStackTrace();
        } finally {
            session.close();
        }
  
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        String mahocphan = mahocphantxt.getText();
        String tenhocphan = tenhocphantxt.getText();
        String sotinchistr =tinchitxt.getText();
        String trongsostr = trongsotxt.getText();
        String vienquanly = vienquanlytxt.getText();
        String thoiluong = thoiluongtxt.getText();
               Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        int sotinchi = 0;
        double trongso = 0;

        if (StringUtils.isEmpty(mahocphan) || StringUtils.isEmpty(tenhocphan) || StringUtils.isEmpty(sotinchistr) || StringUtils.isEmpty(trongsostr) || StringUtils.isEmpty(vienquanly) || StringUtils.isEmpty(thoiluong)) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin học phần!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            if (!StringUtils.isNumeric(sotinchistr) || !sotinchistr.matches("\\d+")) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng định dạng tín chỉ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                sotinchi = Integer.parseInt(sotinchistr);
                if (sotinchi < 1 || sotinchi > 3) {
                    JOptionPane.showMessageDialog(null, "Số tín chỉ phải trong khoảng từ 1 đến 3!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if (!StringUtils.isNumeric(trongsostr)) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng định dạng trọng số!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                trongso = Double.parseDouble(trongsostr);
                if (trongso < 0 || trongso > 1) {
                    JOptionPane.showMessageDialog(null, "Trọng số phải trong khoảng từ 0 đến 1!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
        }
        try {
            tx = session.beginTransaction();
            HocPhanEntity hocphan = (HocPhanEntity) session.get(HocPhanEntity.class, maHp);
            hocphan.setTenHp(tenhocphan);
            hocphan.setThoiLuong(thoiluong);
            hocphan.setTinChi(sotinchi);
            hocphan.setTrongSo(trongso);
            hocphan.setTenKhoa(vienquanly);
            session.update(hocphan);
            tx.commit();
        } catch (HibernateException e) {
            if (tx != null) tx.rollback();
            e.printStackTrace();
        } finally {
            session.close();
        }
        maHp = null;
        mahocphantxt.setText("");
        tenhocphantxt.setText("");
        tinchitxt.setText("");
        trongsotxt.setText("");
        vienquanlytxt.setText("");
        thoiluongtxt.setText("");
        admincontroller.loadtable(modeltable);
    }//GEN-LAST:event_btnluuActionPerformed

    private void trongsotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trongsotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trongsotxtActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        cardlayouttab.removeAll();
        cardlayouttab.add(card1);
        cardlayouttab.repaint();
        cardlayouttab.revalidate();
        admincontroller.loadtableUser(tableUser);
        
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        String mssv = mssvtxt.getText();
        String hoVaTen = hovatentxt.getText();
        String ngaySinhStr = ngaysinhtxt.getText();
        String lop = loptxt.getText();
        String heHoc = hehoctxt.getText();
        String trangThai = (String)combobox.getSelectedItem();
        String email = emailtxt.getText();
        admincontroller.addSinhVien(mssv, hoVaTen, ngaySinhStr, lop, heHoc, trangThai, email);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        mssvtxt.setText(" ");
        hovatentxt.setText(" ");
        ngaysinhtxt.setText(" ");

        loptxt.setText(" ");
        hehoctxt.setText(" ");
        emailtxt.setText("");
    }//GEN-LAST:event_resetbtnActionPerformed
    private void getinfosv() {
        tableUser.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            if (!event.getValueIsAdjusting()) {
                int selectedRow = tableUser.getSelectedRow(); // Lấy chỉ số của hàng được chọn
                String username = (String) tableUser.getValueAt(selectedRow, 0); // Lấy giá trị của ô đầu tiên trong hàng được chọn
                
            }
        }
    });
    }   
    private void btnthemtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemtkActionPerformed
        // TODO add your handling code here:
        cardlayouttab.removeAll();
        cardlayouttab.add(card3);
        cardlayouttab.repaint();
        cardlayouttab.revalidate();
        
    }//GEN-LAST:event_btnthemtkActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        LoginForm formx = new LoginForm();
        formx.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxActionPerformed
    
    private void sinhvienpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinhvienpanelMouseClicked
        // TODO add your handling code here:
        cardlayouttab.removeAll();
        cardlayouttab.add(card5);
        cardlayouttab.repaint();
        cardlayouttab.revalidate();
        admincontroller.getlistsv(tablesinhvien);
    }//GEN-LAST:event_sinhvienpanelMouseClicked

    private void sinhvienpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinhvienpanelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sinhvienpanelMouseEntered

    private void sinhvienpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinhvienpanelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_sinhvienpanelMouseExited

    private void sinhvienpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinhvienpanelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sinhvienpanelMousePressed
   
    private void btnxoasvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoasvActionPerformed
        // TODO add your handling code here:
        admincontroller.xoasv(tablesinhvien);
    }//GEN-LAST:event_btnxoasvActionPerformed

    private void svtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_svtkActionPerformed

    private void svtkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svtkMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_svtkMouseEntered

    private void tkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkActionPerformed
        // TODO add your handling code here:
        String string_input = svtk.getText();
        sinhviencontroller.timKiemSinhVienTheoTuKhoa(string_input,tablesinhvien);
    }//GEN-LAST:event_tkActionPerformed

    private void resetColor() {
        accountPanel.setBackground(new java.awt.Color(64,43,100));
        modulePanel.setBackground(new java.awt.Color(64,43,100));
    }
    /**
     * @param userName
     */
    public static void main(String userName) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminMenu(userName).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel;
    private javax.swing.JButton bntxoa;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthemtk;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnxoasv;
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card2;
    private javax.swing.JPanel card3;
    private javax.swing.JPanel card5;
    private javax.swing.JPanel cardlayouttab;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel hehocLabel;
    private javax.swing.JTextField hehoctxt;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JLabel hotenLabel;
    private javax.swing.JTextField hovatentxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loplabel;
    private javax.swing.JTextField loptxt;
    private javax.swing.JTextField mahocphantxt;
    private javax.swing.JTable modeltable;
    private javax.swing.JPanel modulePanel;
    private javax.swing.JLabel mssvLabel;
    private javax.swing.JTextField mssvtxt;
    private javax.swing.JLabel ngaysinhLabel;
    private javax.swing.JTextField ngaysinhtxt;
    private javax.swing.JButton resetbtn;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel sinhvienpanel;
    private javax.swing.JTextField svtk;
    private javax.swing.JTable tableUser;
    private javax.swing.JTable tablesinhvien;
    private javax.swing.JTextField tenhocphantxt;
    private javax.swing.JTextField thoiluongtxt;
    private javax.swing.JTextField tinchitxt;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JButton tk;
    private javax.swing.JLabel trangthaiLabel;
    private javax.swing.JTextField trongsotxt;
    private javax.swing.JTextField vienquanlytxt;
    // End of variables declaration//GEN-END:variables
}
