/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.HocPhanController;
import entity.DangKyHpEntity;
import entity.HocPhanEntity;
import entity.SinhVienEntity;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.annotations.Parent;
import util.HibernateUtil;
import view.LoginForm;

/**
 *
 * @author Dell
 */
public class StudentMenu extends javax.swing.JFrame {
    private String userName;
    /**
     * Creates new form MainMenu
     */   
    CardLayout cardLayout;    
    private HocPhanController hocphancontroller;
    public StudentMenu(String userName){
        initComponents();
  
        this.userName = userName;
        Session session = HibernateUtil.getSessionFactory().openSession();
        SinhVienEntity sinhvien = (SinhVienEntity)session.createQuery("FROM SinhVienEntity sv WHERE sv.mssv = :username")
                        .setParameter("username", userName)
                        .uniqueResult();

        if (sinhvien != null) {
            hovatentxt.setText(sinhvien.getHoVaTen());
            mssvtxt.setText(sinhvien.getMssv());
            ngaysinhtxt.setText(new SimpleDateFormat("dd-MM-yyyy").format(sinhvien.getNgaySinh()));
            diachitxt.setText(sinhvien.getDiachi());
            hehoctxt.setText(sinhvien.getHeHoc());
            loptxt.setText(sinhvien.getLop());
            sdttxt.setText(sinhvien.getSodienthoai());
            trangthaitxt.setText(sinhvien.getTrangThai());
            
        } else {
            JOptionPane.showMessageDialog(null, "Không tìm thấy sinh viên có username là " + userName);
        }
        setResizable(false);
        helloLabel.setText("<html>Xin chào bạn <b>" + sinhvien.getHoVaTen() + "</b></html>");
        cardLayout = (CardLayout)(cardlayouttab.getLayout());
        cardLayout.show(cardlayouttab,"card1");
        hocphancontroller  = new HocPhanController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        helloLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        sidePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        informationPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        curriculumPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cardlayouttab = new javax.swing.JPanel();
        card1 = new javax.swing.JPanel();
        hotenlabeltxt = new javax.swing.JLabel();
        mssvlabeltxt = new javax.swing.JLabel();
        loplabel = new javax.swing.JLabel();
        ngaysinhlabel = new javax.swing.JLabel();
        hehoclabel = new javax.swing.JLabel();
        trangthailabel = new javax.swing.JLabel();
        diachilabel = new javax.swing.JLabel();
        sdtlabel = new javax.swing.JLabel();
        hovatentxt = new javax.swing.JTextField();
        loptxt = new javax.swing.JTextField();
        mssvtxt = new javax.swing.JTextField();
        ngaysinhtxt = new javax.swing.JTextField();
        sdttxt = new javax.swing.JTextField();
        diachitxt = new javax.swing.JTextField();
        trangthaitxt = new javax.swing.JTextField();
        hehoctxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        card2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dshpsv = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        tkhp = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        card3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dki_hocphantable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        dkhpbtn = new javax.swing.JButton();
        card4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dki_hocphantable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        xoahp = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        titlePanel.setBackground(new java.awt.Color(54, 33, 89));
        titlePanel.setPreferredSize(new java.awt.Dimension(1020, 56));

        helloLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        helloLabel.setForeground(new java.awt.Color(255, 255, 255));
        helloLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap(800, Short.MAX_VALUE)
                .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jButton1))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 55, 118)));

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setLayout(new java.awt.GridLayout(5, 1));

        informationPanel.setBackground(new java.awt.Color(85, 55, 118));
        informationPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        informationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informationPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                informationPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                informationPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                informationPanelMousePressed(evt);
            }
        });
        informationPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Thông tin cá nhân");
        informationPanel.add(jLabel3);

        jPanel2.add(informationPanel);

        curriculumPanel.setBackground(new java.awt.Color(64, 43, 100));
        curriculumPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        curriculumPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                curriculumPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                curriculumPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                curriculumPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                curriculumPanelMousePressed(evt);
            }
        });
        curriculumPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Chương trình đào tạo");
        curriculumPanel.add(jLabel5);

        jPanel2.add(curriculumPanel);

        registerPanel.setBackground(new java.awt.Color(64, 43, 100));
        registerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerPanelMousePressed(evt);
            }
        });
        registerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Đăng ký học tập");
        registerPanel.add(jLabel10);

        jPanel2.add(registerPanel);

        searchPanel.setBackground(new java.awt.Color(64, 43, 100));
        searchPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchPanelMousePressed(evt);
            }
        });
        searchPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 12));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Tra cứu");
        searchPanel.add(jLabel15);

        jPanel2.add(searchPanel);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 176, Short.MAX_VALUE))
        );

        cardlayouttab.setBackground(new java.awt.Color(153, 255, 102));
        cardlayouttab.setLayout(new java.awt.CardLayout());

        card1.setBackground(new java.awt.Color(255, 255, 255));

        hotenlabeltxt.setBackground(new java.awt.Color(255, 255, 255));
        hotenlabeltxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hotenlabeltxt.setText("Họ và tên :  ");

        mssvlabeltxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mssvlabeltxt.setText("Mã số sinh viên :");

        loplabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loplabel.setText("Lớp:");

        ngaysinhlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ngaysinhlabel.setText("Ngày sinh:");

        hehoclabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hehoclabel.setText("Hệ học");

        trangthailabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        trangthailabel.setText("Trạng Thái");

        diachilabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diachilabel.setText("Địa chỉ");

        sdtlabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sdtlabel.setText("Số điện thoại");

        hovatentxt.setEditable(false);

        loptxt.setEditable(false);

        mssvtxt.setEditable(false);

        ngaysinhtxt.setEditable(false);
        ngaysinhtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngaysinhtxtActionPerformed(evt);
            }
        });

        sdttxt.setEditable(false);
        sdttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdttxtActionPerformed(evt);
            }
        });

        diachitxt.setEditable(false);

        trangthaitxt.setEditable(false);
        trangthaitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trangthaitxtActionPerformed(evt);
            }
        });

        hehoctxt.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Thông tin cá nhân");

        javax.swing.GroupLayout card1Layout = new javax.swing.GroupLayout(card1);
        card1.setLayout(card1Layout);
        card1Layout.setHorizontalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hotenlabeltxt)
                    .addComponent(hehoclabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sdtlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diachilabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ngaysinhlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loplabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mssvlabeltxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trangthailabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hovatentxt)
                    .addComponent(mssvtxt)
                    .addComponent(loptxt)
                    .addComponent(ngaysinhtxt)
                    .addComponent(sdttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diachitxt)
                    .addComponent(hehoctxt)
                    .addComponent(trangthaitxt))
                .addGap(304, 304, 304))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(444, 444, 444))
        );
        card1Layout.setVerticalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotenlabeltxt)
                    .addComponent(hovatentxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mssvlabeltxt)
                    .addComponent(mssvtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loplabel)
                    .addComponent(loptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card1Layout.createSequentialGroup()
                        .addComponent(ngaysinhlabel)
                        .addGap(18, 18, 18)
                        .addComponent(diachilabel)
                        .addGap(18, 18, 18)
                        .addComponent(sdtlabel))
                    .addGroup(card1Layout.createSequentialGroup()
                        .addComponent(ngaysinhtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diachitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sdttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(card1Layout.createSequentialGroup()
                        .addComponent(hehoclabel)
                        .addGap(18, 18, 18)
                        .addComponent(trangthailabel))
                    .addGroup(card1Layout.createSequentialGroup()
                        .addComponent(hehoctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(trangthaitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        cardlayouttab.add(card1, "card2");

        card2.setBackground(new java.awt.Color(255, 255, 255));

        dshpsv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã học phần", "Tên học phần", "Số tín chỉ", "Trọng số", "Viện quản lý", "Thời lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dshpsv);

        jLabel4.setBackground(new java.awt.Color(255, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Danh sách học phần");

        jButton3.setText("jButton3");

        jButton4.setText("Tìm kiếm ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card2Layout = new javax.swing.GroupLayout(card2);
        card2.setLayout(card2Layout);
        card2Layout.setHorizontalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                        .addComponent(tkhp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(53, 53, 53))))
            .addGroup(card2Layout.createSequentialGroup()
                .addGap(484, 484, 484)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        card2Layout.setVerticalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tkhp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18))))
        );

        cardlayouttab.add(card2, "card3");

        card3.setBackground(new java.awt.Color(255, 255, 255));

        dki_hocphantable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã học phần", "Tên học phần", "Số tín chỉ", "Trọng số", "Viện quản lý", "Thời lượng", "Lựa chọn đăng kí"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(dki_hocphantable);

        jLabel7.setBackground(new java.awt.Color(255, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Đăng kí học phần");

        dkhpbtn.setText("Đăng kí những học phần đã chọn");
        dkhpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dkhpbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card3Layout = new javax.swing.GroupLayout(card3);
        card3.setLayout(card3Layout);
        card3Layout.setHorizontalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
            .addGroup(card3Layout.createSequentialGroup()
                .addGroup(card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dkhpbtn))
                    .addGroup(card3Layout.createSequentialGroup()
                        .addGap(468, 468, 468)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card3Layout.setVerticalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addGap(44, 44, 44)
                .addComponent(dkhpbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardlayouttab.add(card3, "card3");

        card4.setBackground(new java.awt.Color(255, 255, 255));

        dki_hocphantable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã học phần", "Tên học phần", "Số tín chỉ", "Trọng số", "Viện quản lý", "Thời lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(dki_hocphantable1);

        jLabel9.setBackground(new java.awt.Color(255, 102, 102));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Danh sách học phần đã đăng ký");

        xoahp.setText("Xóa tất cả học phần đã đăng kí");
        xoahp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoahpActionPerformed(evt);
            }
        });

        jButton2.setText("Export file");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card4Layout = new javax.swing.GroupLayout(card4);
        card4.setLayout(card4Layout);
        card4Layout.setHorizontalGroup(
            card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
            .addGroup(card4Layout.createSequentialGroup()
                .addComponent(xoahp)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(card4Layout.createSequentialGroup()
                .addGap(439, 439, 439)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        card4Layout.setVerticalGroup(
            card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(card4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xoahp)
                    .addComponent(jButton2))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cardlayouttab.add(card4, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardlayouttab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(cardlayouttab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void informationPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationPanelMousePressed

        //((CardLayout)mainPanel.getLayout()).show(mainPanel, "accountManagerCard");
        //((CardLayout)accountManager.getLayout()).show(accountManager, "menuAccountCard");
        
    }//GEN-LAST:event_informationPanelMousePressed

    private void curriculumPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curriculumPanelMousePressed
       
        
        //((CardLayout)mainPanel.getLayout()).show(mainPanel, "curriculumCard");
        //((CardLayout)moduleManager.getLayout()).show(moduleManager, "menuCurriculumnCard");
    }//GEN-LAST:event_curriculumPanelMousePressed

    private void informationPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationPanelMouseEntered
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(informationPanel.getBackground().getRGB() != color.getRGB()) {
            informationPanel.setBackground(new java.awt.Color(52,35,82));
        } 
        cardLayout.show(cardlayouttab, "card1");
    }//GEN-LAST:event_informationPanelMouseEntered

    private void informationPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationPanelMouseExited
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(informationPanel.getBackground().getRGB() != color.getRGB()) {
            informationPanel.setBackground(new java.awt.Color(64,43,100));
        } 
    }//GEN-LAST:event_informationPanelMouseExited

    private void curriculumPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curriculumPanelMouseEntered
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(curriculumPanel.getBackground().getRGB() != color.getRGB()) {
            curriculumPanel.setBackground(new java.awt.Color(52,35,82));
        } 
        cardLayout.show(cardlayouttab, "card2");

    }//GEN-LAST:event_curriculumPanelMouseEntered

    private void curriculumPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curriculumPanelMouseExited
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(curriculumPanel.getBackground().getRGB() != color.getRGB()) {
            curriculumPanel.setBackground(new java.awt.Color(64,43,100));
        } 
    }//GEN-LAST:event_curriculumPanelMouseExited

    private void goInformationTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goInformationTabMousePressed
      
    }//GEN-LAST:event_goInformationTabMousePressed

    private void goChangePassTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goChangePassTabMousePressed
 
    }//GEN-LAST:event_goChangePassTabMousePressed

    private void goModuleListTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goModuleListTabMousePressed
       
    }//GEN-LAST:event_goModuleListTabMousePressed

    private void registerPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerPanelMouseEntered
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(registerPanel.getBackground().getRGB() != color.getRGB()) {
            registerPanel.setBackground(new java.awt.Color(52,35,82));
        }
    }//GEN-LAST:event_registerPanelMouseEntered

    private void registerPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerPanelMouseExited
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(registerPanel.getBackground().getRGB() != color.getRGB()) {
            registerPanel.setBackground(new java.awt.Color(64,43,100));
        }
    }//GEN-LAST:event_registerPanelMouseExited

    private void registerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerPanelMousePressed
        resetColor();
        registerPanel.setBackground(new java.awt.Color(85,55,118));
       
    }//GEN-LAST:event_registerPanelMousePressed

    private void goRegisterModuleTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goRegisterModuleTabMousePressed

    }//GEN-LAST:event_goRegisterModuleTabMousePressed

    private void goPersonalTranscriptTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goPersonalTranscriptTabMousePressed
     
    }//GEN-LAST:event_goPersonalTranscriptTabMousePressed

    private void goClassListTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goClassListTabMousePressed
    
    }//GEN-LAST:event_goClassListTabMousePressed

    private void searchPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelMousePressed

    }//GEN-LAST:event_searchPanelMousePressed

    private void searchPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelMouseExited
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(searchPanel.getBackground().getRGB() != color.getRGB()) {
            searchPanel.setBackground(new java.awt.Color(64,43,100));
        }
    }//GEN-LAST:event_searchPanelMouseExited

    private void searchPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelMouseEntered
        java.awt.Color color = new java.awt.Color(85,55,118);
        if(searchPanel.getBackground().getRGB() != color.getRGB()) {
            searchPanel.setBackground(new java.awt.Color(52,35,82));
        }
    }//GEN-LAST:event_searchPanelMouseEntered

    private void informationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationPanelMouseClicked
        // TODO add your handling code here:
        cardlayouttab.removeAll();
        cardlayouttab.add(card1);
        cardlayouttab.repaint();
        cardlayouttab.revalidate();
        
    }//GEN-LAST:event_informationPanelMouseClicked

    private void curriculumPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curriculumPanelMouseClicked
        // TODO add your handling code here:
        cardlayouttab.removeAll();
        cardlayouttab.add(card2);
        cardlayouttab.repaint();
        cardlayouttab.revalidate();
        hocphancontroller.loadhocphantable(dshpsv);
    }//GEN-LAST:event_curriculumPanelMouseClicked

    private void ngaysinhtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngaysinhtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngaysinhtxtActionPerformed

    private void sdttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdttxtActionPerformed

    private void trangthaitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trangthaitxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trangthaitxtActionPerformed

    private void registerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerPanelMouseClicked
        // TODO add your handling code here:
        cardlayouttab.removeAll();
        cardlayouttab.add(card3);
        cardlayouttab.repaint();
        cardlayouttab.revalidate();
        hocphancontroller.loadtable_dki(dki_hocphantable);
    }//GEN-LAST:event_registerPanelMouseClicked


    private void dkhpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dkhpbtnActionPerformed
        // TODO add your handling code here:
        hocphancontroller.dangkihpsv(userName, dki_hocphantable);
    }//GEN-LAST:event_dkhpbtnActionPerformed
   
    private void searchPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPanelMouseClicked
        // TODO add your handling code here:
        cardlayouttab.removeAll();
        cardlayouttab.add(card4);
        cardlayouttab.repaint();
        cardlayouttab.revalidate();
        hocphancontroller.getlisthp_dki(userName, dki_hocphantable1);
    }//GEN-LAST:event_searchPanelMouseClicked
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginForm login_form = new LoginForm();
        this.setVisible(false);
        login_form.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void xoahpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoahpActionPerformed
        // TODO add your handling code here:
        hocphancontroller.xoaallhp_sv(userName);
        hocphancontroller.getlisthp_dki(userName, dki_hocphantable1);
    }//GEN-LAST:event_xoahpActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          File file = new File("dshpdki.txt");
        if (file.exists()) {
            file.delete();
        }
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            // Ghi tiêu đề các cột
            for (int i = 0; i < dki_hocphantable.getColumnCount(); i++) {
                writer.write(dki_hocphantable.getColumnName(i));
                if (i < dki_hocphantable.getColumnCount() - 1) {
                    writer.write("\t");
                }
            }
            writer.newLine();
            // Ghi dữ liệu từng dòng
            for (int i = 0; i < dki_hocphantable.getRowCount(); i++) {
                for (int j = 0; j < dki_hocphantable.getColumnCount(); j++) {
                    Object value = dki_hocphantable.getValueAt(i, j);
                    if (value != null) {
                        writer.write(value.toString());
                    }
                    if (j < dki_hocphantable.getColumnCount() - 1) {
                        writer.write("\t");
                    }
                }
                writer.newLine();
            }
            JOptionPane.showMessageDialog(null, "Export file thành công");
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String timkiem_hp = tkhp.getText();
        hocphancontroller.timkiemhp(timkiem_hp, dshpsv);     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void resetColor() {
        informationPanel.setBackground(new java.awt.Color(64,43,100));
        curriculumPanel.setBackground(new java.awt.Color(64,43,100));
        registerPanel.setBackground(new java.awt.Color(64,43,100));
        //transcriptPanel.setBackground(new java.awt.Color(64,43,100));
        searchPanel.setBackground(new java.awt.Color(64,43,100));
    }
    /**
     * @param userName
     */
    public static void main(String userName) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentMenu(userName).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card2;
    private javax.swing.JPanel card3;
    private javax.swing.JPanel card4;
    private javax.swing.JPanel cardlayouttab;
    private javax.swing.JPanel curriculumPanel;
    private javax.swing.JLabel diachilabel;
    private javax.swing.JTextField diachitxt;
    private javax.swing.JButton dkhpbtn;
    private javax.swing.JTable dki_hocphantable;
    private javax.swing.JTable dki_hocphantable1;
    private javax.swing.JTable dshpsv;
    private javax.swing.JLabel hehoclabel;
    private javax.swing.JTextField hehoctxt;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JLabel hotenlabeltxt;
    private javax.swing.JTextField hovatentxt;
    private javax.swing.JPanel informationPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel loplabel;
    private javax.swing.JTextField loptxt;
    private javax.swing.JLabel mssvlabeltxt;
    private javax.swing.JTextField mssvtxt;
    private javax.swing.JLabel ngaysinhlabel;
    private javax.swing.JTextField ngaysinhtxt;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel sdtlabel;
    private javax.swing.JTextField sdttxt;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField tkhp;
    private javax.swing.JLabel trangthailabel;
    private javax.swing.JTextField trangthaitxt;
    private javax.swing.JButton xoahp;
    // End of variables declaration//GEN-END:variables
}
